### ISSUE TITLE
No wasm backend found.

### ISSUE THREAD

**Issue by gustavoquincy** [dakenf/stable-diffusion-webgpu-minimal#1]
Hello, I'm trying out the WebGPU demo and enabled Experimental WebAssembly and JSPI in the Chromium browser. Having loaded the model, after refreshing the page, I was prompted with 
```
no available backend found. ERR: [wasm] RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.
```
Do you know how to fix it?

**Comment by dakenf** [comment]
Can you open devtools, go to network tab and check why ort-wasm-simd.jsep.wasm could not load?

**Comment by gustavoquincy** [comment]
Thanks for your suggestion, now it's working, just slow.
<img width="833" alt="Screenshot 2023-07-24 at 17 03 01" src="https://github.com/dakenf/stable-diffusion-webgpu-minimal/assets/44153667/f19083a4-8e26-490f-b808-d5aed6cac752">
